apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  labels:
    name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
  serviceName: "user-db"  # Required for StatefulSets to manage network identities
  template:
    metadata:
      labels:
        name: user-db
    spec:
      containers:
      - name: user-db
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.userdb.image.repo }}:{{ .Values.userdb.image.tag }}
        ports:
        - name: mongo
          containerPort: 27017
        resources:
{{ toYaml .Values.userdb.resources | indent 10 }}
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - name: mongo-data
          mountPath: /data/db  # Mount path for MongoDB data directory
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi  # Adjust storage size as needed
